title: Coding Fearlessly
description: Coding Fearlessly - thoughts and code by Mindaugas Mozūras.
url: http://codingfearlessly.com
locale: en_us

author:
  name: Mindaugas Mozūras
  github: mmozuras
  speakerdeck: mmozuras
  rss: //feeds.feedburner.com/CodingFearlessly

permalink: /:title
exclude:
  - README.md
  - Rakefile
  - sass

feed:
  path: atom.xml

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed

defaults:
  -
    scope:
      path: "post"
    values:
      layout: "post"
  -
    scope:
      path: "talk"
    values:
      layout: "post"
